/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qHkUTOwophS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function Component() {
  return (
    <div className="flex flex-col h-screen bg-[#1e1e1e] text-white">
      <header className="bg-[#2b2b2b] p-4 flex items-center">
        <div className="flex items-center gap-2">
          <div className="bg-[#55efc4] text-[#1e1e1e] rounded-full w-8 h-8 flex items-center justify-center text-2xl">
            🤖
          </div>
          <h2 className="text-lg font-medium">ChatGPT</h2>
        </div>
      </header>
      <div className="flex-1 overflow-auto p-4 grid gap-4">
        <div className="flex items-start gap-3">
          <div className="bg-[#55efc4] text-[#1e1e1e] rounded-full w-8 h-8 flex items-center justify-center text-2xl">
            🤖
          </div>
          <div className="bg-[#2b2b2b] px-4 py-3 rounded-2xl max-w-[70%]">
            <p>Hello! How can I assist you today?</p>
          </div>
        </div>
        <div className="flex items-start gap-3 justify-end">
          <div className="bg-[#55efc4] px-4 py-3 rounded-2xl max-w-[70%]">
            <p>Hi there! I'm looking to create a dark-themed chat bot interface.</p>
          </div>
          <div className="bg-[#55efc4] text-[#1e1e1e] rounded-full w-8 h-8 flex items-center justify-center text-2xl">
            😀
          </div>
        </div>
        <div className="flex items-start gap-3">
          <div className="bg-[#55efc4] text-[#1e1e1e] rounded-full w-8 h-8 flex items-center justify-center text-2xl">
            🤖
          </div>
          <div className="bg-[#2b2b2b] px-4 py-3 rounded-2xl max-w-[70%]">
            <p>
              Sounds good! I've put together a dark-themed chat bot interface for you. Let me know if you have any other
              requirements.
            </p>
          </div>
        </div>
      </div>
      <div className="bg-[#2b2b2b] p-4 flex items-center gap-2">
        <input
          type="text"
          placeholder="Type your message..."
          className="bg-[#1e1e1e] px-4 py-2 rounded-full flex-1 focus:outline-none"
        />
        <Button variant="ghost" size="icon" className="rounded-full">
          <SendIcon className="w-4 h-4" />
        </Button>
      </div>
    </div>
  )
}

function SendIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
